### ISSUE TITLE
Suppressed Item

### ISSUE THREAD

**Issue by shanacote** [shanacote/docassemble-scdao#9]
If question is clicked, then the check boxes show up. If not move on

**Comment by shanacote** [comment]
add checkbox - 'was there an evidentiary hearing?' - this will be contingent to other questions, such as item suppressed, etc.
They show up one after another if they are clicked. If not they are not clicked, move to next page

**Comment by joellea** [comment]
made questions about suppressed item contingent upon there being an evidentiary hearing and an item being suppressed
